---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: jet-github-config
  labels:
    app: pgmitche-provider-jet-github
spec:
  image: pgmtiche/provider-jet-github-controller:main
  args: ["-d"]
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: pgmitche-provider-jet-github
spec:
  package: pgmitche/provider-jet-github:main
  controllerConfigRef:
    name: jet-github-config
